### ISSUE TITLE
모터드라이버문의

### ISSUE THREAD

**Issue by turtlebot1024** [Road-Balance/SpotMicroJetson#10]
안녕하세요 
동작중 모터드라이버pca9685가 타는일이생겨문의드립니다.
cls모터를사용하였고 pca에는 약 5V를 V+에연결하여 6개의모터를 동작시켰는데요 
부하를 조금받자마자 드라이버소손이 발생했습니다. 
5V로는 cls모터가충분한출력토크생성을못하는것같은데 혹시 다른방법이있을지문의드립니다. 그리고 충분한 토크생성이안될경우 저와같이 소손이일어날수있는지도궁금합니다. 감사합니다

**Comment by kimsooyoung** [comment]
pca9685가 부하에 대응이 쉽지 않다는 것은 저도 마찬가지였습니다.
때문에, 모든 모터 움직임이 최대한 자유로운 상태에서 작업을 하신 뒤, 이후 충분한 전류를 갖는 전원으로 개발하시기를 추천드립니다.

저의 경우 7.4V Lipo 베터리 + DC/DC Converter를 사용하여 Step Down한 뒤 연결하여 사용하였습니다.
