### ISSUE TITLE
automatic_gait 실행시 kinematics 모듈 실행 불가에러

### ISSUE THREAD

**Issue by aptxlee** [Road-Balance/SpotMicroJetson#4]
안녕하세요  automatic_gait.py를 실행하는데 지속적으로 no moduled not found kinematics.kinematics as kn 에러가 발생합니다. 우선은 지침을 모두 다 따라서 설치 하였지만 해당 임포트 에러가 지속적으로 발생하여 도움을 요청합니다. 제가 어느부분을 잘못한것인가요?

(lee-env) lee@lee-desktop:~/SpotMicroJetson/JetsonNano$ python start_automatic_gait.py
Traceback (most recent call last):
  File "start_automatic_gait.py", line 18, in <module>
    import Kinematics.Kinematics as kn
ModuleNotFoundError: No module named 'Kinematics.Kinematics'

개발환경 :제슨나노 
에러 : kinmatics모듈 로드불가로인한 시스템 구동 불가

**Comment by kimsooyoung** [comment]
안녕하세요 `aptxlee`님 이슈를 공유해주셔서 감사합니다. 우선 해당 모듈이 import 되는 과정을 짚고 넘어가고자 합니다.


* [다음 코드](https://github.com/Road-Balance/SpotMicroJetson/blob/ff864753422b70144ae6fcd4593f1c689b9bbadc/JetsonNano/start_automatic_gait.py#L8)를 보시면 import 할 모듈의 위치로 한단계 위의 상위 디렉토리를 추가하고 있습니다.
```python
from os import system, name 
import sys
sys.path.append("..")
```

그렇기에 `SpotMicroJetson/JetsonNano/` 에서 한 단계 위인 `SpotMicroJetson/`에 위치한 모듈들을 import 할 수 있게 됩니다.

지금 상황에서 `SpotMicroJetson/Kinematics/`를 보시면 아마 다음과 같은 파일들이 보이실 것입니다.

* Kinematic.ipynb
* KinematicMovements.ipynb
* README.md
* kinematicMotion.py
* kinematics.py

이들 중 우리가 import 해야 할 파일 이름은 `kinematics.py`이며, `import Kinematics.kinematics as kn` 와 같이 가져올 수 있습니다.
하지만 `aptxlee`님의 질문을 보면 `import Kinematics.Kinematics as kn`로 되어 있네요

결론적으로, 아래와 같이 K를 소문자로 바꿔주시면 되지 않을까 싶습니다.

```python
# 질문 중
import Kinematics.Kinematics as kn

# 수정 후
import Kinematics.kinematics as kn
```

수정 후, 지속적으로 문제가 발생한다면 피드백을 남겨주세요!! 감사합니다. 👍

**Comment by aptxlee** [comment]
제시하신 방법으로 코드를 변경하여 접근하였지만 같은문제가 계속 발생합니다. 혹시 절대 경로를 지정 넣어서 해도 문제가 없을까요?

**Comment by kimsooyoung** [comment]
해결이 되지 않았다니 죄송합니다 😢 
당장은 다음과 같은 디버깅이 떠오르는데요.

1. `kinematics.py`를 바로 **JetsonNano** 폴더에 복붙
2. 말씀주신 바와 같이 절대경로 지정

저 또한 디버깅하고 있겠습니다. 피드백 남겨주세요!!!

**Comment by aptxlee** [comment]
경과 사항 공유 드립니다. 
우선 기존의 임포트에러 문제는 해결하였습니다우분투 버전문제인가 싶어서 기존의 젯슨이미지가 아닌 강좌 자료에 있는 최신 이미지를 이용해 다시 sd카드를 포팅했으며 venv 를 활성화하고 예제코드를 실행시켜놓으면 해당 에러는 발생하지않았고 제대로 동작하였습니다. 
다만 젯슨 나노의 기본은 파이썬 2.7로 설정되어있어서 이부분이 문제를 일으켰습니다. 그래서 https://seongkyun.github.io/others/2019/05/09/ubuntu_python/ 해당사이트의 방법대로 자동 실행 버전을 바꿔주고 우선 에러를 해결 하였습니다. 개인적으론 코드설명부분에 venv를 계속 활성화 시키고 코드를 실행할것같은 주의 문을 넣어주셔서 내용을 보충해주셨으면 합니다. 유투브영상은 너무길어서요 ㅎ 
그리고 전자부에 각 부분의 어디가 어디로 연결되는지도 설명을 보충해주시면 좀더 좋을 자료가 될것같습니다. 문의에 응답해주셔서 감사드립니다.

**Comment by kimsooyoung** [comment]
오랜 시간동안 고생 많으셨을텐데, 정말 감사드립니다.
동영상 강의는 제 소관이 아니라 수정이 불가하지만, 강의노트를 수정토록 하겠습니다.
전자부 또한 저도 부족함을 느끼고 있는데요, 차후에 설계와 더불어 PCB 제작을 기획하고 있으니 완료되면 추가토록 하겠습니다.

정말 감사드립니다. 좋은 하루 되세요!!! 👍
