### ISSUE TITLE
모터 변경 후 frequency 문제

### ISSUE THREAD

**Issue by jyes90** [Road-Balance/SpotMicroJetson#6]
pca = list()
pca.append(PCA9685(i2c_bus0, address=0x40))
pca[-1].frequency = 330

모터를 CLS-200MD로 변경하여 구동을 하고 있는데, 위 모터는 frequency가 310으로 입력해야 제대로 동작을 합니다.

그래서 start_automatic_gait.py을 실행시키면 over180, under0가 지속적으로 나옵니다.

구동코드에서 frequency를 변경해줘야 할거같은데, 어디서 변경을 진행해야 하는가요?

그리고 확인해보니 CLS-200MD와 MG996R 두가지 모터가 회전방향이 서로 반대인데, 이부분은 어떻게 수정을 해야할까요?

**Comment by ghost** [comment]
안녕하세요,

해당 상황은 저희가 이전에 배포하였던 servo_controller.py 파일의 라이브러리가 calibration 모듈과 맞지 않는 버전으로 배포되어 발생한 것으로 판단됩니다.

프로젝트에 새로운 **servo_controller_fix.py** 파일을 추가하였습니다.
동작은 동일하며, 서보모터 frequency, pulse width 등을 세밀하게 조정할 수 있도록 작성하였습니다.
해당 파일을 이용하여 시도해보시면 좋을 것 같습니다.

모터의 회전 방향이 반대일 경우, 우선적으로 해주셔야 할 작업은 다음과 같습니다.
1. _servo_offsets 의 값들을 바꿔주세요.
`180` -> `1`, `1` -> `180`으로 반대방향으로 바꾸어 주시면 됩니다.

2. thetas의 값의 부호를 바꿔주세요. 
- `self._val_list[0] = self._servo_offsets[0] - self._thetas[0][2]` 에서 `-` 위치의 부호를 모두 뒤집어 바꿔주시거나,
-  thetas 리스트에 모두 -1을 곱해주시면 회전방향을 바꿀 수 있습니다.

감사합니다. :)

**Comment by jyes90** [comment]
감사합니다. 일단 추가해주신 파일로 변경하여 실행을 해보았는데,
Initializing Servos
Initializing ServoKit
Done initializing
Under 0!!
Traceback (most recent call last):
  File "/home/bark/bark/JetsonNano/servo_controller.py", line 109, in <module>
    controller.servoRotate(thetas)
  File "/home/bark/bark/JetsonNano/servo_controller.py", line 96, in servoRotate
    self._kit.servo[x].angle = self._val_list[x]
AttributeError: 'Controllers' object has no attribute '_kit'
Exiting...
Cleaning up pins

이렇게 출력이 되면서 실행이 되질 않네요.

**Comment by ghost** [comment]
안녕하세요,

해당 부분 파일 변경 과정에서 버그가 있었던 것으로 확인됩니다.
버그를 수정한 파일을 다시 업로드 하였습니다.

문제 발생시 문의 부탁드립니다. :)

**Comment by jyes90** [comment]
답변 감사드립니다. 위의 문제는 해결이 되었습니다.
