### ISSUE TITLE
특정 자세 추가 방법.

### ISSUE THREAD

**Issue by jyes90** [Road-Balance/SpotMicroJetson#7]
space를 입력하면 초기 자세로 돌아가는 것 처럼 특정 키를 입력하면 특정자세를 취하도록 하고 싶은데, 

어디를 추가해야하는지 모르겠네요.

multiprocess_kb.py에 while 문 안에 self.resetStatus() 처럼 추가하면 될거같은데, 

특정자세의 각도 등을 어떻게 입력을 해야하는지  감이 안잡히네요.

**Comment by kimsooyoung** [comment]
안녕하세요. 

해당 기능은 강의 내용을 통해 익힌 내용으로 충분히 구현 가능할 것이라 생각됩니다.

 
1. 원하시는 모습에 대한 모터의 각도를 모두 구한 뒤
2. **17강**의 `pose` 제어 방식으로 함수를 구현합니다.
3. **24강**의 키보드 제어 방식을 통해 c가 눌리면 해당 함수로 진입합니다.
4. 이 내용을 시뮬레이션에서 먼저 해보셔도 좋고, 바로 로봇으로 해보셔도 좋을 것 같습니다.

이런 순서로 진행하면 어떨까 싶습니다.
코드를 작성하여 직접 구현하는 것까지는 DH님의 끈기에 달려있다고 생각합니다.

원하시는 기능 구현하시기를 저도 응원하며 좋은 하루되세요 
감사합니다.

김수영 드림
