### ISSUE TITLE
no module

### ISSUE THREAD

**Issue by tc2731** [Road-Balance/SpotMicroJetson#8]
![Screenshot from 2021-06-03 15-32-15](https://user-images.githubusercontent.com/85216296/120598243-fe863b80-c480-11eb-8b7c-722e4b256b35.png)
그림과 같이 모듈이 없다고 나오는데 어떻게 해야 할까요?

**Comment by kimsooyoung** [comment]
please refer this issue

https://github.com/Road-Balance/SpotMicroJetson/issues/4
