### ISSUE TITLE
Pybullet 오동작입니다.

### ISSUE THREAD

**Issue by suyong2** [Road-Balance/SpotMicroJetson#9]
![b](https://user-images.githubusercontent.com/54465738/130747498-588882f2-f6ea-43d7-9451-259b03e87cb0.JPG)
![a](https://user-images.githubusercontent.com/54465738/130747505-710d77ce-717e-4913-8391-b3e20e64e275.JPG)
안녕하세요.
g.camp강의로 알게됐습니다만, Pybullet 시뮬실행하면 첨부사진처럼 공중에떠있어 w,s 눌러도 이동이 안되고 허공에서 동작하는데, 바닥으로 내릴방법은 없는지요?
좋은 강의 감사드리며 방법아시면 답변부탁드리겠습니다.

**Comment by kimsooyoung** [comment]
Sorry for late reply,

If you want the robot to walk on the ground, change below lines as follows

```python
robot=spotmicroai.Robot(True,True,reset)

to 

robot=spotmicroai.Robot(False,True,reset)
```

**Comment by suyong2** [comment]
잘되네요. It works well. Thanks.
